import { PrismaClient } from '@prisma/client';
import { transcribeAudioWithRetry } from '../src/services/audioTranscriptionService';
import openai from '../src/config/openAi';

const prisma = new PrismaClient();

async function generateFillInTheBlanksFromTranscript(
  transcript: string,
): Promise<{ textWithBlanks: string; blanks: any[] }> {
  if (!transcript || typeof transcript !== 'string') {
    throw new Error('Invalid transcript provided');
  }

  try {
    const prompt = `
You are an expert at creating PTE (Pearson Test of English) "Listening Fill in the Blanks" questions.

Given the following audio transcript, create a fill-in-the-blanks exercise by:
1. Selecting 4-6 key words to remove (focus on content words: nouns, verbs, adjectives, adverbs)
2. Avoid removing function words (articles, prepositions, conjunctions) unless they're crucial
3. Choose words that test vocabulary and comprehension
4. Ensure the blanks are distributed throughout the text, not clustered
5. For each blank, provide 3-4 plausible options including the correct answer

Audio Transcript: "${transcript}"

**Rules:**
- Your response MUST be a valid JSON object with exactly this structure:
{
  "textWithBlanks": "The text with _____ where blanks should be",
  "blanks": [
    {
      "position": 1,
      "correctAnswer": "correct_word",
      "options": ["correct_word", "option2", "option3", "option4"]
    }
  ]
}
- Replace selected words with _____ in the textWithBlanks
- Each blank should have 3-4 options total (including the correct answer)
- Options should be shuffled (correct answer not always first)
- Make distractors plausible but clearly incorrect in context
- Ensure the text flows naturally even with blanks

Return only the JSON object, no additional text or explanations.`;

    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: 'You are an expert PTE question creator. Always respond with valid JSON only.',
        },
        {
          role: 'user',
          content: prompt,
        },
      ],
      temperature: 0.3,
      max_tokens: 2000,
    });

    const responseText = completion.choices[0]?.message?.content?.trim();
    if (!responseText) {
      throw new Error('No response from OpenAI');
    }

    console.log('OpenAI response for fill-in-the-blanks:', responseText);

    // Parse the JSON response
    // Remove markdown code block formatting if present
    let jsonString = responseText;
    if (jsonString.startsWith('```json')) {
      jsonString = jsonString.replace(/^```json\n/, '').replace(/\n```$/, '');
    } else if (jsonString.startsWith('```')) {
      jsonString = jsonString.replace(/^```\n/, '').replace(/\n```$/, '');
    }

    const parsedData = JSON.parse(jsonString);

    if (
      !parsedData.textWithBlanks ||
      !parsedData.blanks ||
      !Array.isArray(parsedData.blanks)
    ) {
      throw new Error('Invalid JSON structure returned from OpenAI');
    }

    return {
      textWithBlanks: parsedData.textWithBlanks,
      blanks: parsedData.blanks,
    };
  } catch (error) {
    console.error('Error generating fill-in-the-blanks:', error);
    throw new Error('Failed to generate fill-in-the-blanks content');
  }
}

async function main() {
  console.log('Starting script...');

  const qt = await prisma.questionType.findUnique({
    where: { name: 'LISTENING_FILL_IN_THE_BLANKS' }
  });

  if (!qt) {
    console.log("No such question type found in DB: LISTENING_FILL_IN_THE_BLANKS");
    return;
  }

  // Find all listening FIB questions where options is empty
  const questions = await prisma.question.findMany({
    where: {
      questionTypeId: qt.id,
      OR: [
        { options: { equals: [] } },
        { options: { equals: null } as any } // prisma types can be tricky
      ]
    }
  });

  console.log(`Found ${questions.length} questions to process.`);

  let successCount = 0;
  let failCount = 0;

  for (const question of questions) {
    console.log(`\nProcessing Question ID: ${question.id} (Code: ${question.questionCode})`);

    if (!question.audioUrl) {
      console.log(`- Skipping: No audioUrl found.`);
      failCount++;
      continue;
    }

    try {
      console.log(`- Transcribing audio: ${question.audioUrl}`);
      const transcriptionResult = await transcribeAudioWithRetry(question.audioUrl);
      const audioTranscript = transcriptionResult.text;

      console.log(`- Transcription successful. Generating blanks...`);
      const blanksResult = await generateFillInTheBlanksFromTranscript(audioTranscript);

      const autoGeneratedTextWithBlanks = blanksResult.textWithBlanks;
      const autoGeneratedBlanks = blanksResult.blanks;

      console.log(`- Generated ${autoGeneratedBlanks.length} blanks. Updating database...`);

      // Transform blanks array into the format expected by the database
      const finalOptions = autoGeneratedBlanks.map((blank: any, index: number) => ({
        id: blank.id || `blank_${index + 1}`,
        position: blank.position || index + 1,
        correctAnswer: blank.correctAnswer,
        options: blank.options || [],
      }));

      const finalCorrectAnswers = autoGeneratedBlanks.reduce(
        (acc: any, blank: any, index: number) => {
          acc[`blank${index + 1}`] = blank.correctAnswer;
          return acc;
        },
        {}
      );

      await prisma.question.update({
        where: { id: question.id },
        data: {
          textContent: autoGeneratedTextWithBlanks,
          options: finalOptions,
          correctAnswers: finalCorrectAnswers,
          updatedAt: new Date(),
        }
      });

      console.log(`- Successfully updated question.`);
      successCount++;
    } catch (err: any) {
      console.error(`- Error processing question: ${err.message}`);
      failCount++;
    }

    // Rate limiting delay (3 seconds)
    console.log('- Waiting 3 seconds before next request...');
    await new Promise(r => setTimeout(r, 3000));
  }

  console.log(`\nFinished processing. Success: ${successCount}, Failed: ${failCount}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
